- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: false
  learner_approved: false
  price: $12,195
  price_was:

- title: 250 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: false
  learner_approved: false
  price: $12,195
  price_was: $12,000

- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: false
  price: $12,195
  price_was:

- title: 250 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: true
  price: $12,195
  price_was: $12,000

- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: false
  price: $12,195
  price_was: $12,000

- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: false
  price: $12,195
  price_was: $12,000

- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: false
  price: $12,195
  price_was: $12,000

- title: 450 SX-F Factory Edition
  url: /mx/450-sx-f-factory-edition/
  image: /assets/img/content/bike-item.jpg
  additional: Save $500 Now!
  demo_available: true
  learner_approved: false
  price: $12,195
  price_was: $12,000