# GLOBAL SITE SETTINGS

cname: coastpowersports.yourwebvisual.com

# META
title: Coast Powersports
title_homepage: Coast Powersports
company: Coast Powersports
description:

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/copowsprts-0317
github_repo_name:
jekyll_version: 3.0.3

# MAIN ADDRESS
address: 212 & 218 Main South Road, Morphett Vale, SA 5162

# OFFICES
offices:
  - title: Yamaha Showroom
    address: 212 Main South Road,<br> Morphett Vale, SA 5162
    phone: (08) 8382 5581
    email: hello@coastpowersports.com.au
    trading_hours: "Monday - Friday : 9.00am - 5.30pm<br> Thursday : 9.00am - 7.00pm<br> Saturday : 9.00am - 1.00pm"

  - title: KTM & Kawasaki Showroom
    address: 218 Main South Road,<br> Morphett Vale, SA 5162
    phone: (08) 8382 5581
    email: info@coastpowersports.com.au

# SOCIAL MEDIA
facebook: https://www.facebook.com/coastpowersports/
instagram: https://www.instagram.com/coastpowersports/

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Much Media
  url: http://muchmedia.com.au
  logo: /assets/img/ui/much-media-logo.svg
  description: Website by Much Media